# Generated by Django 4.1.4 on 2022-12-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, choices=[('IR', 'Iran'), ('UK', 'United Kingdom')], max_length=40, null=True),
        ),
    ]
