# Generated by Django 4.1.4 on 2022-12-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, choices=[('IR', 'Iran'), ('UK', 'United Kingdom')], max_length=50, null=True),
        ),
    ]
