# Generated by Django 4.1.4 on 2022-12-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useraddress_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='location',
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, choices=[('IRAN', 'Iran'), ('UNITED STATE', 'United State')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, choices=[('IR', 'Iran'), ('US', 'United State')], max_length=40, null=True),
        ),
    ]
