# Generated by Django 4.1.4 on 2022-12-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_useraddress_location_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
