# Generated by Django 4.1.4 on 2022-12-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentroom',
            name='price_per_night',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)ss_price', to='reservations.price'),
        ),
        migrations.AddField(
            model_name='apartmentreservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='apartment.apartmentroom'),
        ),
    ]
