# Generated by Django 4.1.4 on 2022-12-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentreservation',
            name='reserved_status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('CANCELLED', 'Cancelled'), ('FINISHED', 'Finished'), ('PROBLEM', 'Problem')], default='RESERVED', max_length=15),
        ),
    ]
