# Generated by Django 4.1.4 on 2022-12-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='reservations.placeaddress'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='reservations.placerate'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='reservations.placetype'),
        ),
    ]
