# Generated by Django 4.1.4 on 2022-12-25 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('apartment', '0006_remove_apartmentreservation_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentroom',
            name='price_per_night',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)ss_price', to='reservations.price'),
        ),
    ]
