# Generated by Django 4.1.4 on 2022-12-29 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_alter_apartmentroom_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrating',
            name='rate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
