# Generated by Django 4.1.4 on 2022-12-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0008_alter_apartmentrating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentreservation',
            name='adult_count',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
