# Generated by Django 4.1.4 on 2022-12-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airplane', '0001_initial'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_destination', to='flight.flightaddress'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='flight.flightrate'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_source', to='flight.flightaddress'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='flight.flighttype'),
        ),
    ]
