# Generated by Django 4.1.2 on 2022-12-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('TRANSFER', 'Transfer'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled')], default='FREE', max_length=10),
        ),
    ]
