# Generated by Django 4.1.4 on 2022-12-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0010_alter_shipreservation_adult_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiprating',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
