# Generated by Django 4.1.2 on 2022-12-21 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrating',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='car.car'),
        ),
        migrations.AddField(
            model_name='carrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caraddress',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.location'),
        ),
        migrations.AddField(
            model_name='car',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='car.caraddress'),
        ),
        migrations.AddField(
            model_name='car',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='car.caraddress'),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='reservations.transporttype'),
        ),
        migrations.AddConstraint(
            model_name='carseat',
            constraint=models.UniqueConstraint(fields=('car', 'number'), name='unique_car_seat'),
        ),
        migrations.AddConstraint(
            model_name='carreservation',
            constraint=models.UniqueConstraint(fields=('user', 'seat'), name='unique_user_car_seat'),
        ),
        migrations.AddConstraint(
            model_name='carrating',
            constraint=models.UniqueConstraint(fields=('car', 'user', 'rate'), name='unique_car_user_rate'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['FREE', 'SPACE', 'TRANSFER'])), fields=('driver', 'status'), name='unique_driver_status'),
        ),
    ]
