# Generated by Django 4.1.4 on 2022-12-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.currency')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('currency_from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_from', to='reservations.currency')),
                ('currency_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_to', to='reservations.currency')),
            ],
        ),
    ]
