# Generated by Django 4.1.4 on 2022-12-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportaddress',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.location'),
        ),
        migrations.AddField(
            model_name='price',
            name='currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.currency'),
        ),
        migrations.AddField(
            model_name='placerate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placeaddress',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.location'),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='currency_from',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_from', to='reservations.currency'),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='currency_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_to', to='reservations.currency'),
        ),
    ]
