# Generated by Django 4.1.4 on 2022-12-23 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='currency_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_from', to='reservations.currency'),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='currency_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_to', to='reservations.currency'),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='reservations.currency'),
        ),
        migrations.AlterField(
            model_name='residencetype',
            name='title',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('HOLIDAY', 'Holiday')], max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='transporttype',
            name='title',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=40, unique=True),
        ),
        migrations.AddConstraint(
            model_name='currencyexchangerate',
            constraint=models.UniqueConstraint(fields=('currency_from', 'currency_to'), name='unique_currency_from_currency_to'),
        ),
        migrations.AddConstraint(
            model_name='currencyexchangerate',
            constraint=models.CheckConstraint(check=models.Q(('currency_from', models.F('currency_to')), _negated=True), name='currency_from_and_currency_to_not_be_equal'),
        ),
    ]
