# Generated by Django 4.1.4 on 2023-01-04 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='currency_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_from', to='reservations.currency'),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='currency_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_to', to='reservations.currency'),
        ),
        migrations.AddConstraint(
            model_name='currencyexchangerate',
            constraint=models.UniqueConstraint(fields=('currency_from', 'currency_to'), name='unique_currency_from_currency_to'),
        ),
        migrations.AddConstraint(
            model_name='currencyexchangerate',
            constraint=models.CheckConstraint(check=models.Q(('currency_from', models.F('currency_to')), _negated=True), name='currency_from_and_currency_to_not_be_equal'),
        ),
    ]
