# Generated by Django 4.1.4 on 2022-12-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_currencyexchangerate_currency_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencetype',
            name='title',
            field=models.CharField(choices=[('BUSINESS', 'Business'), ('HOLIDAY', 'Holiday')], max_length=40),
        ),
        migrations.AlterField(
            model_name='transporttype',
            name='title',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=40),
        ),
    ]
