# Generated by Django 4.1.4 on 2022-12-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='max_reservation',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
