# Generated by Django 4.1.4 on 2022-12-20 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='price_per_night',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.price'),
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_reservation', to='hotel.hotelroom'),
        ),
        migrations.AddField(
            model_name='hotelreservation',
            name='total_cost',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='reservations.price'),
        ),
    ]
