# Generated by Django 4.1.2 on 2022-12-21 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelrating',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='hotelrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hoteladdress',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.location'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_address', to='hotel.hoteladdress'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='reservations.placetype'),
        ),
        migrations.AddConstraint(
            model_name='hotelroom',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='unique_hotel_number_seat'),
        ),
        migrations.AddConstraint(
            model_name='hotelreservation',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_user_hotel_room'),
        ),
        migrations.AddConstraint(
            model_name='hotelrating',
            constraint=models.UniqueConstraint(fields=('hotel', 'user', 'rate'), name='unique_hotel_user_rate'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['FREE', 'SPACE', 'FULL'])), fields=('name', 'status'), name='unique_hotel_name_status'),
        ),
    ]
