# Generated by Django 4.1.4 on 2022-12-29 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelrating',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='hotelrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelcomment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_comment', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='hotelcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_%(class)ss', to='hotel.hotelcomment'),
        ),
        migrations.AddField(
            model_name='hotelcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelcomment',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hoteladdress',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.location'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_address', to='hotel.hoteladdress'),
        ),
        migrations.AddConstraint(
            model_name='hotelroom',
            constraint=models.UniqueConstraint(fields=('hotel', 'number'), name='unique_hotel_number_seat'),
        ),
        migrations.AddConstraint(
            model_name='hotelrating',
            constraint=models.UniqueConstraint(fields=('hotel', 'user', 'rate'), name='unique_hotel_user_rate'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.UniqueConstraint(fields=('name', 'residence_status'), name='unique_hotel_name_residence_status'),
        ),
    ]
