# Generated by Django 4.1.4 on 2023-01-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelpassenger',
            options={'ordering': ['-created_time']},
        ),
        migrations.RemoveConstraint(
            model_name='hotelpassenger',
            name='unique_room_user',
        ),
    ]
