# Generated by Django 4.1.4 on 2022-12-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotelreservation_reserved_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreservation',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotelreservation',
            name='check_out_date',
            field=models.DateField(),
        ),
    ]
