# Generated by Django 4.1.4 on 2022-12-30 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotelgallery_alter_hotelroom_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelgallery',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_gallery', to='hotel.hotel'),
        ),
    ]
