# Generated by Django 4.1.4 on 2022-12-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_hotelgallery_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
