# Generated by Django 4.1.4 on 2022-12-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_hotelroom_price_per_night'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hotelreservation',
            name='unique_user_hotel_room',
        ),
        migrations.AddConstraint(
            model_name='hotelreservation',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_user_hotel_room', violation_error_message='Each user has reserved only one room'),
        ),
    ]
