# Generated by Django 4.1.4 on 2022-12-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_hotelimage_is_main'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hotelimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('gallery', 'is_main'), name='just_one_main_image'),
        ),
    ]
