# Generated by Django 4.1.4 on 2022-12-30 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_hotelimage_just_one_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='is_valid',
        ),
    ]
