# Generated by Django 4.1.4 on 2022-12-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_hotelreservation_unique_user_hotel_room_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hotelreservation',
            name='unique_user_hotel_room',
        ),
        migrations.AddConstraint(
            model_name='hotelreservation',
            constraint=models.UniqueConstraint(fields=('user', 'room'), name='unique_user_hotel_room'),
        ),
    ]
