# Generated by Django 4.1.4 on 2022-12-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_remove_hotelreservation_unique_user_hotel_room_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hotelreservation',
            name='unique_user_hotel_room',
        ),
        migrations.AddConstraint(
            model_name='hotelreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('reserved_status__in', ['INITIAL', 'RESERVED'])), fields=('user', 'room'), name='unique_user_hotel_room'),
        ),
    ]
