# Generated by Django 4.1.4 on 2022-12-29 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_remove_hotelreservation_unique_user_hotel_room_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hotelreservation',
            name='unique_user_hotel_room',
        ),
        migrations.AlterField(
            model_name='hotelrating',
            name='rate',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
