# Generated by Django 4.1.4 on 2022-12-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_remove_hotelreservation_unique_user_hotel_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreservation',
            name='adult_count',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
