# Generated by Django 4.1.4 on 2022-12-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttype',
            name='title',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=40),
        ),
    ]
