# Generated by Django 4.1.4 on 2022-12-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useraddress_city'),
        ('flight', '0002_alter_flighttype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightaddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.city'),
        ),
    ]
