# Generated by Django 4.1.4 on 2022-12-29 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utlis.validation_transport_date
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_number', models.IntegerField(default=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('number_reserved', models.PositiveSmallIntegerField(default=0)),
                ('transfer_date', models.DateTimeField(validators=[utlis.validation_transport_date.validation_transport_date])),
                ('transport_status', models.CharField(choices=[('SPACE', 'Space'), ('TRANSFER', 'Transfer'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled')], default='SPACE', max_length=15)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('driver', models.CharField(max_length=50)),
                ('max_reservation', models.PositiveSmallIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='BusAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must not consist of space and requires country code. eg : 989210000000', regex='^[1-9][0-9]{8,14}$')])),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('adult_count', models.PositiveSmallIntegerField()),
                ('children_count', models.PositiveSmallIntegerField(default=0)),
                ('reserved_status', models.CharField(choices=[('INITIAL', 'Initial'), ('RESERVED', 'Reserved'), ('CANCELLED', 'Cancelled'), ('FINISHED', 'Finished'), ('PROBLEM', 'Problem')], default='INITIAL', max_length=15)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('INVALID', 'Invalid'), ('RESERVED', 'Reserved')], default='FREE', max_length=10)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('Bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='bus.bus')),
            ],
        ),
    ]
