# Generated by Django 4.1.4 on 2022-12-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busseat',
            name='price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.price'),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Bus_reservation', to='bus.busseat'),
        ),
    ]
