# Generated by Django 4.1.4 on 2022-12-29 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busrating',
            name='Bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='bus.bus'),
        ),
        migrations.AddField(
            model_name='busrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busaddress',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.location'),
        ),
        migrations.AddField(
            model_name='bus',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='bus.busaddress'),
        ),
        migrations.AddField(
            model_name='bus',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='bus.busaddress'),
        ),
        migrations.AddConstraint(
            model_name='busseat',
            constraint=models.UniqueConstraint(fields=('Bus', 'number'), name='unique_Bus_seat'),
        ),
        migrations.AddConstraint(
            model_name='busreservation',
            constraint=models.UniqueConstraint(fields=('user', 'seat'), name='unique_user_Bus_seat'),
        ),
        migrations.AddConstraint(
            model_name='busrating',
            constraint=models.UniqueConstraint(fields=('Bus', 'user', 'rate'), name='unique_Bus_user_rate'),
        ),
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.UniqueConstraint(condition=models.Q(('transport_status__in', ['SPACE', 'TRANSFER'])), fields=('driver', 'transport_status'), name='unique_driver_transport_status'),
        ),
    ]
