# Generated by Django 4.1.4 on 2022-12-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_alter_bus_number_reserved'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bus',
            name='unique_driver_transport_status',
        ),
        migrations.AlterField(
            model_name='bus',
            name='transport_status',
            field=models.CharField(choices=[('SPACE', 'Space'), ('TRANSFER', 'Transfer'), ('ARRIVED', 'Arrived'), ('CANCELLED', 'Cancelled')], default='SPACE', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.UniqueConstraint(condition=models.Q(('transport_status__in', ['SPACE', 'TRANSFER'])), fields=('driver', 'transport_status'), name='unique_driver_transport_status'),
        ),
    ]
