# Generated by Django 4.1.4 on 2022-12-20 11:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('INVALID', 'Invalid'), ('RESERVED', 'Reserved')], default='FREE', max_length=10)),
                ('pilot', models.CharField(max_length=50)),
                ('number_reserved', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_reservation', models.PositiveSmallIntegerField(default=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirplaneReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_count', models.PositiveSmallIntegerField(default=0)),
                ('children_count', models.PositiveSmallIntegerField(default=0)),
                ('check_source_date', models.DateTimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airplane_reservation', to='airplane.airplane')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
