# Generated by Django 4.1.2 on 2022-12-20 21:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('INVALID', 'Invalid'), ('RESERVED', 'Reserved')], default='FREE', max_length=10)),
                ('pilot', models.CharField(max_length=50)),
                ('number_reserved', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_reservation', models.PositiveSmallIntegerField(default=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirplaneReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_count', models.PositiveSmallIntegerField(default=0)),
                ('children_count', models.PositiveSmallIntegerField(default=0)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('check_source_date', models.DateTimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airplane_reservation', to='airplane.airplane')),
                ('total_cost', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='reservations.price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirplaneRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='airplane.airplane')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirplaneAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must not consist of space and requires country code. eg : 989210000000', regex='^[1-9][0-9]{8,14}$')])),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='airplane',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='airplane.airplaneaddress'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='airplane.airplaneaddress'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='reservations.transporttype'),
        ),
    ]
