# Generated by Django 4.1.4 on 2023-01-05 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airplane', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportaddress',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='reservations.location'),
        ),
        migrations.AddField(
            model_name='airport',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airport', to='airplane.airportaddress'),
        ),
        migrations.AddField(
            model_name='airplaneseat',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='airplane.airplane'),
        ),
        migrations.AddField(
            model_name='airplaneseat',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)ss_price', to='reservations.price'),
        ),
        migrations.AddField(
            model_name='airplanereservation',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airplane_reservation', to='airplane.airplane'),
        ),
    ]
