# Generated by Django 4.1.4 on 2022-12-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
        ('airplane', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplanereservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airplane',
            name='destination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_destination', to='reservations.transportaddress'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='reservations.transportrate'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_source', to='reservations.transportaddress'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to='reservations.transporttype'),
        ),
    ]
