# Generated by Django 4.1.4 on 2023-01-02 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airplane', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airplanereservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airplanepassenger',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='airplane.airplaneseat'),
        ),
        migrations.AddField(
            model_name='airplanecompanyrating',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='airplane.airplanecompany'),
        ),
        migrations.AddField(
            model_name='airplanecompanyrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airplanecompanycomment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='airplane.airplanecompany'),
        ),
        migrations.AddField(
            model_name='airplanecompanycomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_%(class)ss', to='airplane.airplanecompanycomment'),
        ),
        migrations.AddField(
            model_name='airplanecompanycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airplanecompanycomment',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airplanecompany',
            name='airport_terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_terminal', to='airplane.airportterminal'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplane', to='airplane.airplanecompany'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='airplane.airport'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source', to='airplane.airport'),
        ),
        migrations.AddConstraint(
            model_name='airplaneseat',
            constraint=models.UniqueConstraint(fields=('airplane', 'number'), name='unique_airplane_seat'),
        ),
        migrations.AddConstraint(
            model_name='airplanepassenger',
            constraint=models.UniqueConstraint(condition=models.Q(('transfer_status__in', ['INITIAL', 'RESERVED', 'TRANSFER'])), fields=('seat', 'phone'), name='unique_seat_user'),
        ),
        migrations.AddConstraint(
            model_name='airplanecompanyrating',
            constraint=models.UniqueConstraint(fields=('company', 'user', 'rate'), name='unique_company_user_rate'),
        ),
        migrations.AddConstraint(
            model_name='airplane',
            constraint=models.UniqueConstraint(condition=models.Q(('transport_status__in', ['SPACE', 'TRANSFER'])), fields=('pilot', 'transport_status'), name='unique_pilot_transport_status'),
        ),
    ]
