# Generated by Django 4.1.4 on 2022-12-31 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
        ('airplane', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplaneseat',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)ss_price', to='reservations.price'),
        ),
    ]
