# Generated by Django 4.1.4 on 2023-01-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0003_alter_airplaneseat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportterminalcompany',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
