# Generated by Django 4.1.4 on 2023-01-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0004_airplanepassenger_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airplanereservation',
            old_name='adult_count',
            new_name='passenger_count',
        ),
        migrations.RemoveField(
            model_name='airplanereservation',
            name='children_count',
        ),
        migrations.AddField(
            model_name='airplanepassenger',
            name='passenger_type',
            field=models.CharField(choices=[('ADULT', 'Adult'), ('CHILDREN', 'Children')], default='ADULT', max_length=20),
        ),
        migrations.AddField(
            model_name='airplanepassenger',
            name='reserved_key',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airplanepassenger',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airplanepassenger',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='airplanepassenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='airplanepassenger',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
