# Generated by Django 4.1.4 on 2023-01-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0005_rename_adult_count_airplanereservation_passenger_count_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='airplanecompanyrating',
            name='unique_company_user_rate',
        ),
        migrations.AlterField(
            model_name='airplanepassenger',
            name='birth_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='airplanepassenger',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='airplanepassenger',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='airplanepassenger',
            name='national_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='airplaneseat',
            name='status',
            field=models.CharField(choices=[('FREE', 'Free'), ('INITIAL', 'Initial'), ('RESERVED', 'Reserved'), ('PROBLEM', 'Problem')], default='FREE', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='airplanecompanyrating',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique_company_user'),
        ),
    ]
